export default {
	xAxis: {
		domain: [],
		label: '',
		displayLine: true,
		displayZeroLine: true,
		displayGridLines: true,
		displayTickLabels: true,
		displayTicks: true,
		displayLabel: true,
		isZoomable: true,
		format: {},
		tickStep: 0,
	},
	yAxis: {
		domain: [],
		label: '',
		displayLine: true,
		displayZeroLine: true,
		displayGridLines: true,
		displayTickLabels: true,
		displayTicks: true,
		displayLabel: true,
		isZoomable: true,
		format: {},
		tickStep: 0,
	},
	displayTooltips: true,
	decimalSeparator: '',
	thousandSeparator: '',
	displayZoomControls: true,
	onZoomControlClick: () => {},
	onAreaClick: () => {},
	id: 'area-chart',
	selectedAreas: [],
	enableAreasSelection: false,
};
